
spring:
  datasource:
    name: etat_fin_app
    host: localhost
    username: pluralis_etat_fin
    password: dev_etat_fin_app_2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:3306/${spring.datasource.name}?createDatabaseIfNotExist=true
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework: DEBUG